"""Start multiple nanobot bot instances via Docker Compose.

Scans a config directory for config_*.json files, generates a
docker-compose override, and starts one container per bot.

Usage:
    python scripts/start_bots.py                         # start all bots
    python scripts/start_bots.py --bots nano0 nano1      # start specific bots
    python scripts/start_bots.py --down                   # stop all bots
    python scripts/start_bots.py --config-dir /path/to   # custom config dir
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_CONFIG_DIR = Path(r"C:\repos\FHL\Nanobot-Teams\config")
PROJECT_ROOT = Path(__file__).resolve().parent.parent
GENERATED_COMPOSE = PROJECT_ROOT / "docker-compose.bots.yml"
BASE_GATEWAY_PORT = 18790
COPILOT_TOKEN_DIR = Path.home() / ".config" / "litellm" / "github_copilot"


def discover_bots(config_dir: Path) -> list[Path]:
    """Find all config_*.json files in the directory."""
    return sorted(config_dir.glob("config_*.json"))


def bot_name(config_path: Path) -> str:
    """Extract bot name from filename: config_nano0.json -> nano0."""
    return config_path.stem.removeprefix("config_")


def read_gateway_port(config_path: Path, fallback: int) -> int:
    """Read gateway.port from a config file."""
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
        return data.get("gateway", {}).get("port", fallback)
    except (json.JSONDecodeError, OSError):
        return fallback


def get_copilot_token_dir() -> Path | None:
    """Return the host copilot token directory if it exists and contains an access-token."""
    if (COPILOT_TOKEN_DIR / "access-token").is_file():
        return COPILOT_TOKEN_DIR
    return None


def generate_compose(
    configs: list[Path], config_dir: Path, copilot_token_dir: Path | None = None
) -> str:
    """Generate a docker-compose.yml string for the given bot configs."""
    lines = [
        "# Auto-generated by scripts/start_bots.py — do not edit manually.",
        "",
        "services:",
    ]

    for i, config_path in enumerate(configs):
        name = bot_name(config_path)
        port = read_gateway_port(config_path, BASE_GATEWAY_PORT + i)

        volumes = [f"      - {config_dir.as_posix()}:/data"]
        if copilot_token_dir:
            volumes.append(
                f"      - {copilot_token_dir.as_posix()}:/root/.config/litellm/github_copilot"
            )

        lines.extend(
            [
                f"  {name}:",
                f"    container_name: nanobot-{name}",
                "    build:",
                f"      context: {PROJECT_ROOT.as_posix()}",
                "      dockerfile: Dockerfile",
                f'    command: ["gateway", "--config", "/data/{config_path.name}"]',
                "    restart: unless-stopped",
                "    volumes:",
                *volumes,
                "    ports:",
                f'      - "{port}:{port}"',
                "    deploy:",
                "      resources:",
                "        limits:",
                '          cpus: "1"',
                "          memory: 1G",
                "        reservations:",
                '          cpus: "0.25"',
                "          memory: 256M",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Start nanobot bot instances via Docker Compose")
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=DEFAULT_CONFIG_DIR,
        help=f"Directory containing config_*.json files (default: {DEFAULT_CONFIG_DIR})",
    )
    parser.add_argument(
        "--bots",
        nargs="*",
        help="Bot names to start (e.g. nano0 nano1). Default: all found configs.",
    )
    parser.add_argument(
        "-d",
        "--detach",
        action="store_true",
        help="Run containers in background",
    )
    parser.add_argument(
        "--down",
        action="store_true",
        help="Stop and remove bot containers",
    )
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="Skip docker image rebuild",
    )
    args = parser.parse_args()

    if not shutil.which("docker"):
        print("Error: docker not found in PATH", file=sys.stderr)
        sys.exit(1)

    # Stop containers
    if args.down:
        if not GENERATED_COMPOSE.exists():
            print(f"Error: {GENERATED_COMPOSE} not found, nothing to stop", file=sys.stderr)
            sys.exit(1)
        cmd = ["docker", "compose", "-f", str(GENERATED_COMPOSE), "down"]
        print(f"[>] {' '.join(cmd)}")
        sys.exit(subprocess.call(cmd))

    if not args.config_dir.is_dir():
        print(f"Error: config directory not found: {args.config_dir}", file=sys.stderr)
        sys.exit(1)

    configs = discover_bots(args.config_dir)
    if not configs:
        print(f"Error: no config_*.json files in {args.config_dir}", file=sys.stderr)
        sys.exit(1)

    # Filter by --bots if specified
    if args.bots:
        selected = set(args.bots)
        configs = [c for c in configs if bot_name(c) in selected]
        if not configs:
            print(f"Error: no matching configs for: {args.bots}", file=sys.stderr)
            sys.exit(1)

    # Skip empty config files
    valid = []
    for c in configs:
        if c.stat().st_size <= 2:
            print(f"[{bot_name(c)}] Skipping (empty config)")
        else:
            valid.append(c)

    if not valid:
        print("Error: no valid (non-empty) configs to start", file=sys.stderr)
        sys.exit(1)

    # Check port conflicts — refuse to start if any two bots share a port
    ports: dict[int, str] = {}
    conflicts = []
    for i, c in enumerate(valid):
        port = read_gateway_port(c, BASE_GATEWAY_PORT + i)
        if port in ports:
            conflicts.append(f"  {bot_name(c)} and {ports[port]} both use port {port}")
        ports[port] = bot_name(c)

    if conflicts:
        print("Error: gateway.port conflicts detected:", file=sys.stderr)
        for msg in conflicts:
            print(msg, file=sys.stderr)
        print(
            "\nFix gateway.port in the config files so each bot has a unique port.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Detect shared Copilot token
    copilot_dir = get_copilot_token_dir()
    if copilot_dir:
        print(f"[+] Copilot auth: shared from {copilot_dir}")
    else:
        print("[!] Copilot auth: not found — each container will need separate login")

    # Generate compose file
    compose_content = generate_compose(valid, args.config_dir, copilot_dir)
    GENERATED_COMPOSE.write_text(compose_content, encoding="utf-8")
    print(f"[+] Generated {GENERATED_COMPOSE}")
    print(f"[+] Bots: {', '.join(bot_name(c) for c in valid)}")
    print(f"[+] Ports: {', '.join(f'{n}={p}' for p, n in sorted(ports.items()))}")
    print()

    # Start
    cmd = ["docker", "compose", "-f", str(GENERATED_COMPOSE), "up"]
    if args.detach:
        cmd.append("-d")
    if not args.no_build:
        cmd.append("--build")

    print(f"[>] {' '.join(cmd)}")
    sys.exit(subprocess.call(cmd))


if __name__ == "__main__":
    main()
